### ISSUE TITLE
关于指针的疑惑

### ISSUE THREAD

**Issue by lemonxia** [JessonYue/LeetCodeLearning#10]
问题类型：链表、指针
问题：删除链表中指定的节点，操作完成后是否应该返回链表？
自我理解：返回不返回其实都一样，指针操作的都是传进来的这个链表。代码如下：

//删除指定的节点
void deleteNode(LinkedList_* list,Node_* node){
    Node_* cur = list->head;
    while(cur->next!=NULL)
    {
        cur = cur->next;
        if(cur->next->data == node->data)
        {
            break;
        }
    }
    Node_* del = cur->next;
    Node_* aft = del->next;
    cur->next = aft;
    list->length -=1;
}

疑惑：不知道是不是这样理解的，还是涉及编码规范应该写返回值？（添加同理）望路哥指点。

**Comment by JessonYue** [comment]
对的 你的理解是对的 C语言往往很少返回，因为操作的参数就是指针。

**Comment by JessonYue** [comment]
![image](https://user-images.githubusercontent.com/25720897/84395267-8e0f5a80-ac30-11ea-81f7-25b87ab35969.png)
