### ISSUE TITLE
爬楼梯算法-c++语法问题

### ISSUE THREAD

**Issue by Feature211** [JessonYue/LeetCodeLearning#3]
#include <iostream>

using namespace std;

int climbStairs(int n);

int main() {
    cout << "Hello, World!" << endl;

    int number = 15;
    int value = climbStairs(number);
    cout << "返回值为："<< value << endl;
    return 0;
}

int climbStairs(int n) {

    if( n == 0 || n == 1 || n == 2){
        return n;
    }
    int num[] = {1,2};
    for (int i = 2; i < n; ++i) {
        num[i] = num[i-1] + num[i-2];
        cout << "当前值为：" << num[i] <<endl;
    }

    return num[n-1];

}

main函数中调用的  int value = climbStairs(number);没有返回值？

**Comment by JessonYue** [comment]
what do you mean？ @Feature211

**Comment by Feature211** [comment]
@JessonYue value值为空，是哪行代码写的有问题吗？路哥

**Comment by yanghaohao** [comment]
你这个似乎没给数组扩容吧

**Comment by JessonYue** [comment]
数组在c语言里必须指定长度，修改num为num［15］
