### ISSUE TITLE
路哥 读书中我产生了一个问题

### ISSUE THREAD

**Issue by xiaozongt1989** [JessonYue/LeetCodeLearning#5]
读完全篇并没有明白有符号数到无符号数的隐式转化会造成什么问题？

读到这个问题时，感觉解释的比较模糊，并且没有真正去提取造成的问题点，所以无法理解问题点在哪里， 而后面解释又很模糊，感觉完全没有理解到转化后问题再在哪里？

看完这两个例子 和后面的解释 还是没有感觉到文中所说的细微的差距在哪里？

**Comment by 997262600** [comment]
我的理解如下，这里以一个例子来说明，如果有不对的，请大家指出
当我们比较两个数的时候：

int a = -1;     //有符号
unsigned b = 3; //无符号

if(a > b){
   //负数大于正数了？？
}

这里在比较运算的时候，就会隐式的将有符号的变量a转换成无符号的

然而-1在计算机中的表示为：1111 1111 1111 1111，是以补码的形式表示

求补码步骤为：
-1的原码：           1000 0000 0000 0001    //最高位1代码符号位(负权)
取-1的绝对值1的原码：0000 0000 0000 0001
将其转换为反码：     1111 1111 1111 1110
加1得到补码：        1111 1111 1111 1111

那么把他看成无符号数则就是65535

65535当然是大于3了，所以结果和我们的预期不一样

以上仅供参考………………。

**Comment by xiaozongt1989** [comment]
这个问题 我已经解决了
